#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY ["Catalog/Catalog.Host/Catalog.Host.csproj", "Catalog/Catalog.Host/"]
COPY ["Infrastructure/Infrastructure/Infrastructure.csproj", "Infrastructure/Infrastructure/"]
RUN dotnet restore "Catalog/Catalog.Host/Catalog.Host.csproj"
COPY . .
WORKDIR "/src/Catalog/Catalog.Host"
RUN dotnet build "Catalog.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Catalog.Host.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Catalog.Host.dll"]

LABEL "project"="iStore_Catalog.Host"
