// <auto-generated />
using Catalog.Host.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Host.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("catalog_brand_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("catalog_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("catalog_type_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("Catalog.Host.Data.Entities.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "catalog_brand_hilo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CatalogBrand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A4Tech"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aorus"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bloody"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Edifier"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gigabyte"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hator"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Honor"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Huawei"
                        },
                        new
                        {
                            Id = 12,
                            Name = "HyperX"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Keychron"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kingston"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 17,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Razer"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Seagate"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 22,
                            Name = "SteelSeries"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Varmilo"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Western Digital"
                        });
                });

            modelBuilder.Entity("Catalog.Host.Data.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "catalog_hilo");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogBrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Warranty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogBrandId");

                    b.HasIndex("CatalogTypeId");

                    b.ToTable("Catalog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 1,
                            CatalogBrandId = 7,
                            CatalogTypeId = 20,
                            Description = "R1700BTs Active Bluetooth Bookshelf Speakers - 2.0 Wireless Near Field Studio Monitor Speaker - 66w RMS with Subwoofer Line Out. BLUETOOTH 5.0 WITH QUALCOMM APTX HD. SUB OUT. NATURAL SOUND REPRODUCTION. UPDATED WIRELESS REMOTE. 2 YEAR WARRANTY.",
                            Name = "R1700BTs",
                            PictureFileName = "r1700bts.webp",
                            Price = 4599.00m,
                            Warranty = 12
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 6,
                            CatalogBrandId = 16,
                            CatalogTypeId = 23,
                            Description = "C270 HD Webcam, HD 720p, Widescreen HD Video Calling, HD Light Correction, Noise-Reducing Mic, For Skype, FaceTime, Hangouts, WebEx, PC/Mac/Laptop/Macbook/Tablet - Black. The C270 HD Webcam gives you sharp, smooth conference calls (720p/30fps) in a widescreen format. Automatic light correction shows you in lifelike, natural colors.",
                            Name = "C270",
                            PictureFileName = "c270hd.webp",
                            Price = 1299.00m,
                            Warranty = 12
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 5,
                            CatalogBrandId = 14,
                            CatalogTypeId = 7,
                            Description = "K3 Version 2 - 75% Layot 84 Keys Ultra-Slim Wireless Bluetooth/USB Wired Mechanical Keyboard with RGB LED Backlit, Low-Profile Keychron Optical Hot-Swappable Brown Switches, Aluminium Frame, Compatible with Mac & Windows.",
                            Name = "K3 Version 2",
                            PictureFileName = "k3version2.webp",
                            Price = 2990.00m,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 5,
                            CatalogBrandId = 14,
                            CatalogTypeId = 7,
                            Description = "Q1 - QMK Custom Mechanical Keyboard - Fully Assembled - Wired USB - Gateron Phantom Brown - Navy Blue. A fully customizable 75% layout mechanical keyboard packed with all premium features and unlimited possibilities.",
                            Name = "Q1",
                            PictureFileName = "q1qmk.webp",
                            Price = 4700.00m,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 1,
                            CatalogBrandId = 14,
                            CatalogTypeId = 7,
                            Description = "Q2 - QMK Custom Mechanical Keyboard - Fully Assembled - Wired USB - Gateron G Pro Brown - Carbon Black. The Q2 is a fully customizable mechanical keyboard with a compact layout that pushes your typing experience to the next level. With a 65% layout, full metal body, double-gasket design, the Q2 is designed for a personalized experience and premium typing comfort.",
                            Name = "Q2",
                            PictureFileName = "q2qmk.webp",
                            Price = 4800.00m,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 2,
                            CatalogBrandId = 16,
                            CatalogTypeId = 7,
                            Description = "K360 Wireless USB Desktop Keyboard — Compact Full Keyboard, 3-Year Battery Life (Glossy Black). K360 is ready when you are. This compact wireless keyboard is ideal for narrower built and allows you to perform even in constricted workspaces. Equipped with a number pad and 12 easy access keys, you can be more productive - at home or at work.",
                            Name = "K360",
                            PictureFileName = "k360.webp",
                            Price = 1399.00m,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 7,
                            CatalogBrandId = 16,
                            CatalogTypeId = 7,
                            Description = "MX Keys Advanced Wireless Illuminated Keyboard, Tactile Responsive Typing, Backlighting, Bluetooth, USB-C, Apple macOS, Microsoft Windows, Linux, iOS, Android, Metal Build - Graphite. Logitech’s most advanced typing experience yet. MX Keys combines crafted keys with smart illumination and a remarkably solid build.",
                            Name = "MX Keys Advanced",
                            PictureFileName = "mxkeys.webp",
                            Price = 2999.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 2,
                            CatalogBrandId = 18,
                            CatalogTypeId = 7,
                            Description = "BlackWidow V3 Tenkeyless TKL Mechanical Gaming Keyboard: Green Mechanical Switches - Tactile & Clicky - Chroma RGB Lighting - Compact Form Factor - Programmable Macros. Compact gaming keyboard featuring Razer Mechanical Switches, customizable lighting powered by Razer Chroma RGB, and aluminum construction for amazing gaming experience.",
                            Name = "BlackWidow V3",
                            PictureFileName = "blackwidowv3tkl.webp",
                            Price = 2799.00m,
                            Warranty = 24
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 4,
                            CatalogBrandId = 23,
                            CatalogTypeId = 7,
                            Description = "Miya68-C Summit Series Wired Mechanical Keyboard. Dye-sub on the top printing.",
                            Name = "Miya68-C Summit Series EC V2 Daisy",
                            PictureFileName = "miya68csummitecswitchv2.webp",
                            Price = 5900.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 10,
                            AvailableStock = 2,
                            CatalogBrandId = 23,
                            CatalogTypeId = 7,
                            Description = "MA87 Lovebirds-You Series Wired Mechanical Keyboard. Five-sides dye-sub printing.",
                            Name = "MA87 Lovebirds-You Series EC V2 Daisy",
                            PictureFileName = "ma87lovebirdsyou.webp",
                            Price = 6100.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 11,
                            AvailableStock = 4,
                            CatalogBrandId = 23,
                            CatalogTypeId = 7,
                            Description = "MA87M V2 Summit Series R2 EC V2 Daisy Wired USB Mechanical Keyboard. Dye-sub on the top printing.",
                            Name = "MA87M V2 Summit Series R2 EC V2 Daisy",
                            PictureFileName = "ma87mv2summitr2ecv2daisy.webp",
                            Price = 6000.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 12,
                            AvailableStock = 1,
                            CatalogBrandId = 23,
                            CatalogTypeId = 7,
                            Description = "VA104S Phoenix Series Wired Mechanical Keyboard. EC V2 Daisy. Five-sides dye-sub printing.",
                            Name = "VA104S Phoenix Series EC V2 Daisy",
                            PictureFileName = "va104sphoenix.webp",
                            Price = 6300.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 13,
                            AvailableStock = 3,
                            CatalogBrandId = 23,
                            CatalogTypeId = 7,
                            Description = "VBM108V2 Crane of Lure Series EC V2 Daisy Wired Mechanical Keyboard. Dye-sub on the top printing.",
                            Name = "VBM108V2 Crane of Lure Series EC V2 Daisy",
                            PictureFileName = "vbm108v2craneoflure.webp",
                            Price = 6800.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 14,
                            AvailableStock = 3,
                            CatalogBrandId = 16,
                            CatalogTypeId = 13,
                            Description = "G305 LIGHTSPEED Wireless Gaming Mouse, Hero 12K Sensor, 12,000 DPI, Lightweight, 6 Programmable Buttons, 250h Battery Life, On-Board Memory, PC/Mac - Blue. LIGHTSPEED wireless gaming mouse designed for serious performance with latest technology innovations. Impressive 250-hour battery life. Now in a variety of vibrant colors.",
                            Name = "G305 LIGHTSPEED",
                            PictureFileName = "g305lightspeedblue.webp",
                            Price = 1899.00m,
                            Warranty = 12
                        },
                        new
                        {
                            Id = 15,
                            AvailableStock = 4,
                            CatalogBrandId = 16,
                            CatalogTypeId = 13,
                            Description = "G502 SE HERO High Performance RGB Gaming Mouse with 11 Programmable Buttons USB Black/White. G502 SE HERO features an advanced optical sensor for maximum tracking accuracy, customizable RGB lighting, custom game profiles, from 200 up to 25,600 DPI, and repositionable weights.",
                            Name = "G502 SE HERO",
                            PictureFileName = "g502sehero.webp",
                            Price = 1699.00m,
                            Warranty = 36
                        },
                        new
                        {
                            Id = 16,
                            AvailableStock = 4,
                            CatalogBrandId = 16,
                            CatalogTypeId = 8,
                            Description = "MX Master 3 Advanced Wireless Mouse, Ultrafast Scrolling, Ergonomic, 4000 DPI, Customization, USB-C, Bluetooth, USB, Apple Mac, Microsoft PC Windows, Linux, iPad - Graphite. An advanced, precise mouse designed for creatives and engineered for coders, featuring a side wheel for extra comfort and a natural feel.",
                            Name = "MX Master 3 Advanced",
                            PictureFileName = "mxmaster3.webp",
                            Price = 2899.00m,
                            Warranty = 36
                        });
                });

            modelBuilder.Entity("Catalog.Host.Data.Entities.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "catalog_type_hilo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CatalogType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Case"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desk Mount"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gamepad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Graphics Card (GPU)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hard-Disk Drive (HDD)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Memory (RAM)"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 14,
                            Name = "MousePad"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Processor (CPU)"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Power Supply Unit (PSU)"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Solid-State Drive (SSD)"
                        },
                        new
                        {
                            Id = 18,
                            Name = "SmartPhone"
                        },
                        new
                        {
                            Id = 19,
                            Name = "SmartWatch"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Subwoofer"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Web Camera"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Wrist Rest"
                        });
                });

            modelBuilder.Entity("Catalog.Host.Data.Entities.CatalogItem", b =>
                {
                    b.HasOne("Catalog.Host.Data.Entities.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Host.Data.Entities.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });
#pragma warning restore 612, 618
        }
    }
}
